# Generated by Django 5.1.3 on 2025-05-02 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('physical_activity_level', models.CharField(max_length=20)),
                ('sleep_hours', models.IntegerField()),
                ('quality_of_sleep', models.IntegerField()),
                ('stress_level', models.CharField(max_length=20)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('blood_pressure_category', models.CharField(max_length=30)),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('daily_steps', models.IntegerField()),
                ('sleep_disorder', models.CharField(max_length=30)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
